language: node_js
node_js:
  - node
install:
  - yarn
script:
  - yarn lint
  - yarn test
  - yarn coverage
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
